name: Run Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - name: Create a .version.js file
        run: |
          touch .version.js && echo "echo \"export const version = 'test'\" > .version.js" | bash -
      - name: Run tests
        run: yarn test:unit:ci
  test-web-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - name: Create a .version.js file
        run: |
          touch .version.js && echo "echo \"export const version = 'test'\" > .version.js" | bash -
      - name: Run tests
        run: yarn test:unit:web-components
  build:
    runs-on: ubuntu-latest
    needs: [test-unit, test-web-components]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - name: Create a .version.js file
        run: |
          touch .version.js && echo "echo \"export const version = 'test'\" > .version.js" | bash -
      - name: Build
        run: yarn build
