name: Run Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  delete-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: SuperViz-Dev
          issue_number: ${{ github.event.number }}
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install
      - name: Create a .version.js file
        run: |
          touch .version.js && echo "echo \"export const version = 'test'\" > .version.js" | bash -
      - name: Create a .remote-config.js file
        run: |
          touch .remote-config.js && echo "echo \"module.exports = { remoteConfig: { apiUrl: 'https://dev.nodeapi.superviz.com', conferenceLayerUrl: 'https://video-frame.superviz.com/lab/index.html'}};\" > .remote-config.js" | bash -
      - name: Run tests
        run: yarn test:unit:ci --coverage
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          lcov-file: ./coverage/lcov.info
  test-web-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install
      - name: Create a .version.js file
        run: |
          touch .version.js && echo "echo \"export const version = 'test'\" > .version.js" | bash -
      - name: Run tests
        run: yarn test:unit:web-components:coverage
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          lcov-file: ./coverage-components/lcov.info
  build:
    runs-on: ubuntu-latest
    needs: [test-unit, test-web-components]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install
      - name: Create a .version.js file
        run: |
          touch .version.js && echo "echo \"export const version = 'test'\" > .version.js" | bash -
      - name: Create a .remote-config.js file
        run: |
          touch .remote-config.js && echo "echo \"module.exports = { remoteConfig: { apiUrl: 'https://dev.nodeapi.superviz.com', conferenceLayerUrl: 'https://video-frame.superviz.com/lab/index.html'}};\" > .remote-config.js" | bash -
      - name: Build
        run: yarn build
